Repository ArashKazemzadeh/AMPMI, pull requests merged in 2024-12, with the labels that each got.

#37 Develop create area for admin 20241201
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/AdminPanelController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/HomeController.cs
  AMPMI/WebSite.EndPoint/Startup.cs
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj.user
Labels: enhancement

#38 Developers
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/AdminPanelController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/HomeController.cs
  AMPMI/WebSite.EndPoint/Controllers/AboutUsController.cs
  AMPMI/WebSite.EndPoint/Startup.cs
  AMPMI/WebSite.EndPoint/Views/AboutUs/Index.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_Layout.cshtml
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj.user
  AMPMI/WebSite.EndPoint/wwwroot/css/site.css
  AMPMI/WebSite.EndPoint/wwwroot/css/style.css
  AMPMI/WebSite.EndPoint/wwwroot/images/76.jpg
Labels: enhancement

#39 init Login and register forms with controller (mobile input , otp con…
  AMPMI/WebSite.EndPoint/Controllers/LoginController.cs
  AMPMI/WebSite.EndPoint/Controllers/RegisterController.cs
  AMPMI/WebSite.EndPoint/Views/Login/ConfirmOTP.cshtml
  AMPMI/WebSite.EndPoint/Views/Login/Login.cshtml
  AMPMI/WebSite.EndPoint/Views/Login/MoblieInput.cshtml
  AMPMI/WebSite.EndPoint/Views/Register/ConfirmOTP.cshtml
  AMPMI/WebSite.EndPoint/Views/Register/MoblieInput.cshtml
  AMPMI/WebSite.EndPoint/Views/Register/Register.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_Layout.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_LayoutLogin.cshtml
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj.user
  AMPMI/WebSite.EndPoint/wwwroot/css/main.css
  AMPMI/WebSite.EndPoint/wwwroot/css/now-ui-kit.css
  AMPMI/WebSite.EndPoint/wwwroot/fonts/iranyekan/eot/iranyekanwebbold(fanum).eot
  AMPMI/WebSite.EndPoint/wwwroot/fonts/iranyekan/eot/iranyekanweblight(fanum).eot
  AMPMI/WebSite.EndPoint/wwwroot/fonts/iranyekan/eot/iranyekanwebregular(fanum).eot
  AMPMI/WebSite.EndPoint/wwwroot/fonts/iranyekan/ttf/iranyekanwebbold(fanum).ttf
  AMPMI/WebSite.EndPoint/wwwroot/fonts/iranyekan/ttf/iranyekanweblight(fanum).ttf
  AMPMI/WebSite.EndPoint/wwwroot/fonts/iranyekan/ttf/iranyekanwebregular(fanum).ttf
  AMPMI/WebSite.EndPoint/wwwroot/fonts/iranyekan/woff/iranyekanwebbold(fanum).woff
  AMPMI/WebSite.EndPoint/wwwroot/fonts/iranyekan/woff/iranyekanweblight(fanum).woff
  AMPMI/WebSite.EndPoint/wwwroot/fonts/iranyekan/woff2/iranyekanwebbold(fanum).woff2
  AMPMI/WebSite.EndPoint/wwwroot/fonts/iranyekan/woff2/iranyekanweblight(fanum).woff2
  AMPMI/WebSite.EndPoint/wwwroot/fonts/iranyekan/woff2/iranyekanwebregular(fanum).woff2
  AMPMI/WebSite.EndPoint/wwwroot/fonts/nucleo-outline.eot
  AMPMI/WebSite.EndPoint/wwwroot/fonts/nucleo-outline.ttf
  AMPMI/WebSite.EndPoint/wwwroot/fonts/nucleo-outline.woff
  AMPMI/WebSite.EndPoint/wwwroot/fonts/nucleo-outline.woff2
  AMPMI/WebSite.EndPoint/wwwroot/js/main.js
  AMPMI/WebSite.EndPoint/wwwroot/js/now-ui-kit.js
Labels: enhancement

#43 init sms service
  AMPMI/AQS_Aplication/Interfaces/IInfrastructure/IAuthenticationOTPService/IAuthenticationOTP.cs
  AMPMI/AQS_Aplication/Interfaces/IInfrastructure/IContext/IDbAmpmiContext.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/IThirdParitesServices/ISMSOTPService.cs
  AMPMI/AQS_Aplication/Services/BannerService.cs
  AMPMI/AQS_Aplication/Services/BlogService.cs
  AMPMI/AQS_Aplication/Services/CategoryService.cs
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/AQS_Aplication/Services/NotificationService.cs
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/AQS_Aplication/Services/SMSOTPService.cs
  AMPMI/AQS_Aplication/Services/SeenNotifByCompanyService.cs
  AMPMI/AQS_Aplication/Services/SubCategoryService.cs
  AMPMI/AQS_Persistence/Contexts/SqlServer/DbAmpmiContext.cs
  AMPMI/ThirdParties/SMSService/AuthenticationOTP.cs
  AMPMI/ThirdParties/SMSService/Models/VerifySendModel.cs
  AMPMI/ThirdParties/SMSService/Models/VerifySendParameterModel.cs
  AMPMI/ThirdParties/ThirdParties.csproj
  AMPMI/WebSite.EndPoint/Controllers/RegisterController.cs
  AMPMI/WebSite.EndPoint/Startup.cs
  AMPMI/WebSite.EndPoint/Views/Register/ConfirmOTP.cshtml
  AMPMI/WebSite.EndPoint/Views/Register/MoblieInput.cshtml
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
Labels: enhancement

#44 init sms service
  AMPMI/AQS_Aplication/Interfaces/IInfrastructure/IAuthenticationOTPService/IAuthenticationOTP.cs
  AMPMI/AQS_Aplication/Interfaces/IInfrastructure/IContext/IDbAmpmiContext.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/IThirdParitesServices/ISMSOTPService.cs
  AMPMI/AQS_Aplication/Services/BannerService.cs
  AMPMI/AQS_Aplication/Services/BlogService.cs
  AMPMI/AQS_Aplication/Services/CategoryService.cs
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/AQS_Aplication/Services/NotificationService.cs
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/AQS_Aplication/Services/SMSOTPService.cs
  AMPMI/AQS_Aplication/Services/SeenNotifByCompanyService.cs
  AMPMI/AQS_Aplication/Services/SubCategoryService.cs
  AMPMI/AQS_Persistence/Contexts/SqlServer/DbAmpmiContext.cs
  AMPMI/ThirdParties/SMSService/AuthenticationOTP.cs
  AMPMI/ThirdParties/SMSService/Models/VerifySendModel.cs
  AMPMI/ThirdParties/SMSService/Models/VerifySendParameterModel.cs
  AMPMI/ThirdParties/ThirdParties.csproj
  AMPMI/WebSite.EndPoint/Controllers/RegisterController.cs
  AMPMI/WebSite.EndPoint/Startup.cs
  AMPMI/WebSite.EndPoint/Views/Register/ConfirmOTP.cshtml
  AMPMI/WebSite.EndPoint/Views/Register/MoblieInput.cshtml
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
Labels: enhancement

#48 Developers
  AMPMI/AMPMI.sln
Labels: bug

#51 init admin view and layout
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/AdminPanelController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/AdminPanel/Panel.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
  AMPMI/WebSite.EndPoint/wwwroot/css/AdminLTE.css
  AMPMI/WebSite.EndPoint/wwwroot/css/adminlte.css.map
  AMPMI/WebSite.EndPoint/wwwroot/css/bootstrap-theme.css
  AMPMI/WebSite.EndPoint/wwwroot/css/customize-adminlte.css
  AMPMI/WebSite.EndPoint/wwwroot/css/ionicons.min.css
  AMPMI/WebSite.EndPoint/wwwroot/css/rtl.css
  AMPMI/WebSite.EndPoint/wwwroot/css/skin-blue.min.css
  AMPMI/WebSite.EndPoint/wwwroot/js/admin/bootstrap.min.js
  AMPMI/WebSite.EndPoint/wwwroot/js/admin/jquery.min.js
  AMPMI/WebSite.EndPoint/wwwroot/js/admin/jquery.min.map
  AMPMI/WebSite.EndPoint/wwwroot/js/adminlte.min.js
Labels: enhancement

#54 refactoring pre registering
  AMPMI/AQS_Aplication/Dtos/RegisterIdentityDTO.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/ICompanyService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/IThirdParitesServices/ISMSOTPService.cs
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/AQS_Aplication/Services/IdentityServices/RegistrationService.cs
  AMPMI/AQS_Aplication/Services/SMSOTPService.cs
  AMPMI/AQS_Common/Services/ValidationService.cs
  AMPMI/WebSite.EndPoint/Controllers/LoginController.cs
  AMPMI/WebSite.EndPoint/Controllers/RegisterController.cs
  AMPMI/WebSite.EndPoint/Models/AcountingViewModel/Register/ConfirmOtpViewModel.cs
  AMPMI/WebSite.EndPoint/Models/AcountingViewModel/Register/CreateCompanyMV.cs
  AMPMI/WebSite.EndPoint/ServicesConfigs/DependencyInjectionConfig.cs
  AMPMI/WebSite.EndPoint/Views/Login/Login.cshtml
  AMPMI/WebSite.EndPoint/Views/Register/ConfirmOTP.cshtml
  AMPMI/WebSite.EndPoint/Views/Register/MobileInput.cshtml
Labels: Refactor

#55 Develop company controller 20241208
  AMPMI/WebSite.EndPoint/Controllers/CompanyController.cs
  AMPMI/WebSite.EndPoint/Models/CompanyViewModel/CompanyDetailVM.cs
  AMPMI/WebSite.EndPoint/Models/CompanyViewModel/CompanyVM.cs
  AMPMI/WebSite.EndPoint/Models/ProductViewModel/ProductVM.cs
  AMPMI/WebSite.EndPoint/Views/Company/CompanyDetail.cshtml
  AMPMI/WebSite.EndPoint/Views/Company/CompanyList.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_Layout.cshtml
Labels: enhancement

#62 Develop company detail 20241217
  AMPMI/WebSite.EndPoint/Views/Company/CompanyDetail.cshtml
Labels: enhancement

#64 Develop category view 20241221
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/CategoryController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/CategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/wwwroot/css/datatables.min.css
  AMPMI/WebSite.EndPoint/wwwroot/js/datatables.min.js
Labels: enhancement

#65 Atiye-Banner-View-20241221
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/BannerController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Banner/BannerList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/wwwroot/css/CustomDashboard.css
  AMPMI/WebSite.EndPoint/wwwroot/images/editing.png
Labels: enhancement

#66 Add ProductsList Action and View
  AMPMI/AQS_Aplication/Interfaces/IServisces/IProductService.cs
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/WebSite.EndPoint/Controllers/CompanyController.cs
  AMPMI/WebSite.EndPoint/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Models/ProductViewModel/ProductVM.cs
  AMPMI/WebSite.EndPoint/ServicesConfigs/DependencyInjectionConfig.cs
  AMPMI/WebSite.EndPoint/Views/Home/Index.cshtml
  AMPMI/WebSite.EndPoint/Views/Product/ProductsList.cshtml
Labels: enhancement

#67 Create Admin notif Page
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/NotificationController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/CategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Notification/ShowPage.cshtml
Labels: enhancement

#69 Atiye_Admin_CSS_AboutUS
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/AboutusController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Aboutus/ShowAboutUs.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/CategoryList.cshtml
  AMPMI/WebSite.EndPoint/wwwroot/css/CustomDashboard.css
  AMPMI/WebSite.EndPoint/wwwroot/images/cancel.png
Labels: enhancement

#80 Atiye-Css-UserList-EditUser-20241223
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/UserController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/CategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Notification/ShowPage.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/SubCategory/SubCategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/EditUser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/UserList.cshtml
  AMPMI/WebSite.EndPoint/wwwroot/css/CustomDashboard.css
Labels: enhancement

#85 Atiye-Notif-UserList-Categorylist-CompanyTeaser
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Notification/ShowPage.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/SubCategory/SubCategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/UserList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyTeaser/EditCompanyTeaser.cshtml
Labels: enhancement

#86 Atiye-ProductList-EditProduct
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/ProductList.cshtml
Labels: enhancement

#87 Add Notif Panel
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/NotificationController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Notification/NotifList.cshtml
Labels: enhancement

#88 Farshid change password 20241224
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/AdminPanelController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/AdminPanel/ChangePassword.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/ChangePassword.cshtml
Labels: enhancement

#89 Arash login 20241228
  AMPMI/AMPMI.sln
  AMPMI/AQS_Aplication/AQS_Application.csproj
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/NotificationDtos/NotificationReadAdminDto.cs
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/ProductDtos/CreateProductDto.cs
  AMPMI/AQS_Aplication/Dtos/IdentityServiceDto/LoginResultDto.cs
  AMPMI/AQS_Aplication/Dtos/IdentityServiceDto/RegisterIdentityDTO.cs
  AMPMI/AQS_Aplication/Dtos/IdentityServiceDto/ResultRegisterIdentityDto.cs
  AMPMI/AQS_Aplication/Interfaces/IInfrastructure/IAuthenticationOTPService/IAuthenticationOTP.cs
  AMPMI/AQS_Aplication/Interfaces/IInfrastructure/IContext/IDbAmpmiContext.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IBannerService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IBlogPictureService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IBlogService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ICategoryService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ICompanyPictureService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ICompanyService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/INotificationService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IProductService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ISeenNotifByCompanyService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ISiteAdminService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ISubCategoryService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/IThirdParitesServices/ISMSOTPService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/IdentityServices/ILoginService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/IdentityServices/IRegistrationService.cs
  AMPMI/AQS_Aplication/Services/BannerService.cs
  AMPMI/AQS_Aplication/Services/BlogService.cs
  AMPMI/AQS_Aplication/Services/CategoryService.cs
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/AQS_Aplication/Services/IdentityServices/LoginService.cs
  AMPMI/AQS_Aplication/Services/IdentityServices/RegistrationService.cs
  AMPMI/AQS_Aplication/Services/NotificationService.cs
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/AQS_Aplication/Services/SMSOTPService.cs
  AMPMI/AQS_Aplication/Services/SeenNotifByCompanyService.cs
  AMPMI/AQS_Aplication/Services/SubCategoryService.cs
  AMPMI/AQS_Persistence/AQS_Persistence.csproj
  AMPMI/AQS_Persistence/Contexts/SqlServer/DbAmpmiContext.cs
  AMPMI/ThirdParties/SMSService/AuthenticationOTP.cs
  AMPMI/ThirdParties/ThirdParties.csproj
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/NotificationController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Notification/NotificationReadByAdminVM.cs
  AMPMI/WebSite.EndPoint/Containers/ContextContainer.cs
  AMPMI/WebSite.EndPoint/Containers/IocContainer.cs
  AMPMI/WebSite.EndPoint/Controllers/CompanyController.cs
  AMPMI/WebSite.EndPoint/Controllers/LoginController.cs
  AMPMI/WebSite.EndPoint/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Controllers/RegisterController.cs
  AMPMI/WebSite.EndPoint/Models/AcountingViewModel/Login/LoginVM.cs
  AMPMI/WebSite.EndPoint/Models/AcountingViewModel/Register/ConfirmOtpViewModel.cs
  AMPMI/WebSite.EndPoint/Models/AcountingViewModel/Register/CreateCompanyMV.cs
  AMPMI/WebSite.EndPoint/Program.cs
  AMPMI/WebSite.EndPoint/Views/Login/ConfirmOTP.cshtml
  AMPMI/WebSite.EndPoint/Views/Login/Login.cshtml
  AMPMI/WebSite.EndPoint/Views/Login/MobileInput.cshtml
  AMPMI/WebSite.EndPoint/Views/Register/Register.cshtml
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
Labels: enhancement

#93 Farshid company product controller 20241228
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IProductService.cs
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/Product/ListProductVM.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/Product/ProductVM.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Containers/IocContainer.cs
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
Labels: enhancement

#94 Farshid company notif controller 20241225
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ISeenNotifByCompanyService.cs
  AMPMI/AQS_Aplication/Services/SeenNotifByCompanyService.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/NotificationController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/NotifVM.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Notification/NotifList.cshtml
  AMPMI/WebSite.EndPoint/Containers/IocContainer.cs
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
Labels: enhancement
