Repository ArashKazemzadeh/AMPMI, pull requests merged in 2025-01, with the labels that each got.

#98 Develop Company Teaser Actions
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditTeaser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyTeaser/EditCompanyTeaser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Shared/_layout.cshtml
Labels: enhancement

#99 Farshid productcontroller 20250104
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/CategoryDtos/CategoryIncludeSubCategoriesDto.cs
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/CategoryDtos/CategoryReadDto.cs
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/SubCategoryDto/SubCategoryReadDto.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ICategoryService.cs
  AMPMI/AQS_Aplication/Services/CategoryService.cs
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Product/ProductVM.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/Product/ProductVM.cs
  AMPMI/WebSite.EndPoint/Utility/FileService.cs
  AMPMI/WebSite.EndPoint/Utility/videoService.cs
Labels: Refactor

#100 Arash new category 20250105
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/CategoryDtos/GetPictureeResultDto.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ICategoryService.cs
  AMPMI/AQS_Aplication/Services/CategoryService.cs
  AMPMI/AQS_Aplication/Services/SubCategoryService.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/CategoryController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/SubCategoryController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Category/CategoryEditVM.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Category/CategoryReadVM.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/SubCategory/ListSubCategoryVM.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/SubCategory/SubCategoryVM.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/CategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/Edit.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/SubCategory/EditSubCategory.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/SubCategory/SubCategoryList.cshtml
  AMPMI/WebSite.EndPoint/Utility/FileService.cs
Labels: enhancement

#101 Save Company Teaser Video
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyTeaserController.cs
Labels: enhancement

#105 Arash company profile 20250105
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/Company/CompanyEditProfileDto.cs
  AMPMI/AQS_Aplication/Interfaces/IInfrastructure/IContext/IDbAmpmiContext.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ICompanyService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/IdentityServices/ILoginService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/IdentityServices/IRegistrationService.cs
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/AQS_Aplication/Services/IdentityServices/LoginService.cs
  AMPMI/AQS_Aplication/Services/IdentityServices/RegistrationService.cs
  AMPMI/AQS_Aplication/Services/MiscellaneousDataService.cs
  AMPMI/AQS_Persistence/Contexts/SqlServer/DbAmpmiContext.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/AboutusController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Aboutus/ShowAboutUs.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyPictureController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/Company/CompanyEditProfileVM.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/Profile/PasswordEditVm.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/ChangePassword.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditCompanyProfile.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Containers/ContextContainer.cs
  AMPMI/WebSite.EndPoint/Containers/IocContainer.cs
  AMPMI/WebSite.EndPoint/Controllers/AboutUsController.cs
  AMPMI/WebSite.EndPoint/Controllers/LoginController.cs
  AMPMI/WebSite.EndPoint/Controllers/RegisterController.cs
  AMPMI/WebSite.EndPoint/Views/AboutUs/Index.cshtml
  AMPMI/WebSite.EndPoint/Views/Register/Register.cshtml
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
Labels: Task

#106 end Task
  AMPMI/AQS_Aplication/Interfaces/IServisces/IdentityServices/ILoginService.cs
  AMPMI/AQS_Aplication/Services/IdentityServices/LoginService.cs
  AMPMI/AQS_Common/Services/ConvertDateService.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Shared/_layout.cshtml
Labels: Task

#108 comit ended
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IBannerService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/IdentityServices/ILoginService.cs
  AMPMI/AQS_Aplication/Services/BannerService.cs
  AMPMI/AQS_Aplication/Services/IdentityServices/LoginService.cs
  AMPMI/AQS_Domin/Entities/Banner.cs
  AMPMI/AQS_Persistence/Configs/EntitiesConfig.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/BannerController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Banner/MultiBannerViewModel.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Banner/BannerList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Containers/IocContainer.cs
  AMPMI/WebSite.EndPoint/Utility/videoService.cs
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
Labels: enhancement

#109 Final Debug For Category , SubCategory and Product
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ICategoryService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ICompanyService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ISubCategoryService.cs
  AMPMI/AQS_Aplication/Services/CategoryService.cs
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/AQS_Aplication/Services/SubCategoryService.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/CategoryController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/SubCategoryController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/Product/ProductVM.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditTeaser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Containers/IocContainer.cs
  AMPMI/WebSite.EndPoint/Utility/FileService.cs
  AMPMI/WebSite.EndPoint/Utility/videoService.cs
Labels: enhancement

#110 Add CompanyPicture Conttoller because it was deleted , and some debug…
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyPicureController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyPicture/Pictures.cshtml
Labels: enhancement

#111 Atiye-20250106-UIChangeHomePage
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Aboutus/ShowAboutUs.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/AdminPanel/ChangePassword.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/Edit.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/ChangePassword.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Notification/NotifList.cshtml
  AMPMI/WebSite.EndPoint/Views/Register/Register.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_Layout.cshtml
  AMPMI/WebSite.EndPoint/wwwroot/css/CustomDashboard.css
  AMPMI/WebSite.EndPoint/wwwroot/css/CustomLogin.css
Labels: enhancement

#113 Add userData if user is logged in
  AMPMI/WebSite.EndPoint/Models/ViewComponents/ProfileVM.cs
  AMPMI/WebSite.EndPoint/ViewComponents/ProfileViewComponent.cs
  AMPMI/WebSite.EndPoint/Views/Shared/Components/Profile/Default.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_Layout.cshtml
Labels: enhancement

#114 Debug Save And Edit For Product And Subcategory
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/SubCategoryController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/SubCategory/SubCategoryVM.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/NotConfirmedProductList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/SubCategory/EditSubCategory.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/ProductController.cs
Labels: enhancement

#116 Atiye-20250107-1617-PageNameForAll
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Aboutus/ShowAboutUs.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/AdminPanel/ChangePassword.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Banner/BannerList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Blog/BlogList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Blog/EditBlog.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/CategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/Edit.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Notification/ShowPage.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/NotConfirmedProductList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/SubCategory/EditSubCategory.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/SubCategory/SubCategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/EditUser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/UserList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyPicture/Pictures.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/ChangePassword.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditCompanyProfile.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditTeaser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Notification/NotifList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/wwwroot/css/CustomDashboard.css
Labels: enhancement

#117 edit Banner list view and aboutus table design
  AMPMI/AQS_Domin/Entities/MiscellaneousData.cs
  AMPMI/AQS_Persistence/Configs/EntitiesConfig.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Banner/BannerList.cshtml
  AMPMI/WebSite.EndPoint/ViewComponents/ProfileViewComponent.cs
Labels: enhancement

#118 Debug Company Notif SeenData Action
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ISeenNotifByCompanyService.cs
  AMPMI/AQS_Aplication/Services/SeenNotifByCompanyService.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyPanelController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/NotificationController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/NotifVM.cs
Labels: bug

#120 Get Data for category , company , banner and blog and show them in view
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/BlogDtos/BlogReadHomeDto.cs
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/Company/CompanyReadDto.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IBlogService.cs
  AMPMI/AQS_Aplication/Services/BlogService.cs
  AMPMI/AQS_Domin/Entities/Blog.cs
  AMPMI/AQS_Domin/Entities/BlogPicture.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Containers/IocContainer.cs
  AMPMI/WebSite.EndPoint/Controllers/HomeController.cs
  AMPMI/WebSite.EndPoint/Models/HomeViewModel/HomeVM.cs
  AMPMI/WebSite.EndPoint/Views/Home/Index.cshtml
Labels: enhancement

#121 Bring ProductList action and view to develop because it been merged t…
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ICompanyService.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IProductService.cs
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/WebSite.EndPoint/Controllers/CompanyController.cs
  AMPMI/WebSite.EndPoint/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Models/CompanyViewModel/CompanyDetailVM.cs
  AMPMI/WebSite.EndPoint/Models/ProductViewModel/ProductDetailVM.cs
  AMPMI/WebSite.EndPoint/Models/ProductViewModel/ProductVM.cs
  AMPMI/WebSite.EndPoint/Views/Company/CompanyDetail.cshtml
  AMPMI/WebSite.EndPoint/Views/Home/Index.cshtml
  AMPMI/WebSite.EndPoint/Views/Product/ProductDetail.cshtml
  AMPMI/WebSite.EndPoint/Views/Product/ProductList.cshtml
Labels: enhancement

#124 Arash isuue22 20250111
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/AdminPanelController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/AdminPanel/ChangePassword.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
Labels: bug

#127 Change all DataTables language to Farsi
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Blog/BlogList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/CategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/NotConfirmedProductList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/SubCategory/SubCategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/UserList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyPicture/Pictures.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Views/AboutUs/Index.cshtml
  AMPMI/WebSite.EndPoint/Views/Home/Index.cshtml
Labels: enhancement

#130 Develop Blog controller
  AMPMI/WebSite.EndPoint/Controllers/BlogController.cs
  AMPMI/WebSite.EndPoint/Models/Blog/BlogDetailVM.cs
  AMPMI/WebSite.EndPoint/Views/Blog/ShowBlog.cshtml
  AMPMI/WebSite.EndPoint/Views/Home/Index.cshtml
Labels: enhancement

#133 end task
  AMPMI/AQS_Aplication/Interfaces/IInfrastructure/IContext/IDbAmpmiContext.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IProductService.cs
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/AQS_Domin/Entities/Blog.cs
  AMPMI/AQS_Domin/Entities/BlogPicture.cs
  AMPMI/AQS_Domin/Entities/Category.cs
  AMPMI/AQS_Domin/Entities/Company.cs
  AMPMI/AQS_Domin/Entities/CompanyPicture.cs
  AMPMI/AQS_Domin/Entities/MiscellaneousData.cs
  AMPMI/AQS_Domin/Entities/Product.cs
  AMPMI/AQS_Domin/Entities/ProductPicture.cs
  AMPMI/AQS_Persistence/Configs/EntitiesConfig.cs
  AMPMI/AQS_Persistence/Contexts/SqlServer/DbAmpmiContext.cs
Labels: Refactor

#136 Save And Delete for company tel and banner
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/Company/CompanyEditProfileDto.cs
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/AQS_Domin/Entities/Company.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/UserList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/Company/CompanyEditProfileVM.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditCompanyProfile.cshtml
Labels: enhancement

#137 Refactor EditUser admin view and add Banner and Tel for save
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/UserController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Company/CompanyVM.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/EditUser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditCompanyProfile.cshtml
  AMPMI/WebSite.EndPoint/Controllers/CompanyController.cs
  AMPMI/WebSite.EndPoint/Models/CompanyViewModel/CompanyDetailVM.cs
  AMPMI/WebSite.EndPoint/Views/Company/CompanyDetail.cshtml
Labels: enhancement

#138 Show product pictures in home ProductDetail , CompanyDetail , Product…
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/WebSite.EndPoint/Controllers/CompanyController.cs
  AMPMI/WebSite.EndPoint/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Models/ProductViewModel/ProductDetailVM.cs
  AMPMI/WebSite.EndPoint/Views/Product/ProductDetail.cshtml
Labels: enhancement

#140 Arash blog 20250117
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/BlogDtos/BlogReadHomeDto.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IBlogService.cs
  AMPMI/AQS_Aplication/Services/BlogService.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/BlogController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/CategoryController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Blog/BlogList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Blog/EditBlog.cshtml
  AMPMI/WebSite.EndPoint/WebSite.EndPoint.csproj
Labels: enhancement

#141 Debug Notif And not confirmed products
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ISeenNotifByCompanyService.cs
  AMPMI/AQS_Aplication/Services/NotificationService.cs
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/AQS_Aplication/Services/SeenNotifByCompanyService.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/NotificationController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Notification/NotificationReadByAdminVM.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Notification/NotifList.cshtml
Labels: enhancement

#142 Debug Company List page - show data
  AMPMI/WebSite.EndPoint/Controllers/CompanyController.cs
  AMPMI/WebSite.EndPoint/Models/CompanyViewModel/CompanyVM.cs
  AMPMI/WebSite.EndPoint/Views/Company/CompanyList.cshtml
Labels: enhancement

#143 Atiye-20250118-1657-CSSChanges
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/EditUser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditCompanyProfile.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Notification/NotifList.cshtml
  AMPMI/WebSite.EndPoint/Views/AboutUs/Index.cshtml
  AMPMI/WebSite.EndPoint/Views/Home/Index.cshtml
  AMPMI/WebSite.EndPoint/wwwroot/css/AdminLTE.css
Labels: enhancement

#144 Debug Company teaser and pictures gallary
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyPictureController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyPicture/Pictures.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditTeaser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Shared/_layout.cshtml
Labels: enhancement

#145 Debug save picture for product and category
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/CategoryController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Category/CategoryEditVM.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/ProductController.cs
Labels: enhancement

#146 Farshid show confirmed products 20250119
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IProductService.cs
  AMPMI/AQS_Aplication/Services/ProductService.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Controllers/CompanyController.cs
  AMPMI/WebSite.EndPoint/Controllers/ProductController.cs
Labels: enhancement

#148 Farshid save and show blog 20250119
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IBlogService.cs
  AMPMI/AQS_Aplication/Services/BlogService.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/BlogController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Blog/BlogList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Blog/EditBlog.cshtml
  AMPMI/WebSite.EndPoint/Controllers/HomeController.cs
  AMPMI/WebSite.EndPoint/Views/Home/Index.cshtml
Labels: enhancement

#149 Save website field for company
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/Company/CompanyEditProfileDto.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ICompanyService.cs
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/AQS_Domin/Entities/Company.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/Company/CompanyEditProfileVM.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditCompanyProfile.cshtml
  AMPMI/WebSite.EndPoint/Controllers/CompanyController.cs
  AMPMI/WebSite.EndPoint/Controllers/HomeController.cs
  AMPMI/WebSite.EndPoint/Models/CompanyViewModel/CompanyDetailVM.cs
  AMPMI/WebSite.EndPoint/Models/CompanyViewModel/CompanyVM.cs
  AMPMI/WebSite.EndPoint/Views/Company/CompanyDetail.cshtml
  AMPMI/WebSite.EndPoint/Views/Company/CompanyList.cshtml
Labels: enhancement

#150 Atiye-20250120-1639-CssChange
  AMPMI/WebSite.EndPoint/Views/Product/ProductDetail.cshtml
  AMPMI/WebSite.EndPoint/Views/Product/ProductList.cshtml
Labels: enhancement

#151 Farshid delete banner 20250120
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/BannerController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Banner/BannerList.cshtml
  AMPMI/WebSite.EndPoint/Controllers/HomeController.cs
Labels: enhancement

#152 Delete company banner from everywhere
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/Company/CompanyEditProfileDto.cs
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/AQS_Domin/Entities/Company.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/UserController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Company/CompanyVM.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/EditUser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/Company/CompanyEditProfileVM.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditCompanyProfile.cshtml
Labels: enhancement

#153 Require picture for product and also fix some other bugs when saving …
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Views/Company/CompanyDetail.cshtml
Labels: enhancement

#154 Debug save and edit company
  AMPMI/AQS_Aplication/Services/IdentityServices/RegistrationService.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/UserController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Company/CompanyVM.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/EditUser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Models/Company/CompanyEditProfileVM.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditCompanyProfile.cshtml
Labels: enhancement

#155 main search company
  AMPMI/AQS_Aplication/Dtos/BaseServiceDto/Company/CompanySearchDto.cs
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/ICompanyService.cs
  AMPMI/AQS_Aplication/Services/CompanyService.cs
  AMPMI/WebSite.EndPoint/Controllers/CompanyController.cs
  AMPMI/WebSite.EndPoint/Views/Company/CompanyList.cshtml
Labels: enhancement

#157 Fix layout of company and admin
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Notification/NotifList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_Layout.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_LayoutLogin.cshtml
  AMPMI/WebSite.EndPoint/wwwroot/blog/blog-1.jpg
  AMPMI/WebSite.EndPoint/wwwroot/blog/blog-2.jpg
  AMPMI/WebSite.EndPoint/wwwroot/blog/blog-3.jpg
Labels: enhancement

#158 Fix companyDetail and company pictures style
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyPicture/Pictures.cshtml
  AMPMI/WebSite.EndPoint/Views/Company/CompanyDetail.cshtml
Labels: enhancement

#159 Save photo and video both for banners
  AMPMI/AQS_Aplication/Interfaces/IServisces/BaseServices/IBannerService.cs
  AMPMI/AQS_Aplication/Services/BannerService.cs
  AMPMI/AQS_Domin/Entities/Banner.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/BannerController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Banner/MultiBannerViewModel.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Banner/BannerList.cshtml
  AMPMI/WebSite.EndPoint/Views/Home/Index.cshtml
Labels: enhancement

#160 Add Enum for picture folders and also debug edit category
  AMPMI/AQS_Common/Enums/FolderNamesEnum.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/BannerController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/BlogController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/CategoryController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/UserController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyPictureController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/CompanyProfileController.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/ProductController.cs
Labels: enhancement

#161 User Teaser And Pictures in UserList Admin
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/UserController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Company/CompanyPictureVM.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Models/Company/CompanyTeaserVM.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/CompanyPictures.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/CompanyTeaser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/EditUser.cshtml
Labels: enhancement

#162 Atiye_20250125_1642_CSSChange
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Blog/EditBlog.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Views/Blog/ShowBlog.cshtml
  AMPMI/WebSite.EndPoint/Views/Company/CompanyDetail.cshtml
  AMPMI/WebSite.EndPoint/Views/Company/CompanyList.cshtml
  AMPMI/WebSite.EndPoint/Views/Home/Index.cshtml
  AMPMI/WebSite.EndPoint/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_Layout.cshtml
  AMPMI/WebSite.EndPoint/wwwroot/css/CustomDashboard.css
Labels: enhancement

#163 Get user products and edit them by admin in userList
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/ProductController.cs
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/EditUser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Controllers/ProductController.cs
Labels: enhancement

#164 Blog list in home page , and also debug edit blog
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/BlogController.cs
  AMPMI/WebSite.EndPoint/Controllers/BlogController.cs
  AMPMI/WebSite.EndPoint/Models/Blog/BlogVM.cs
  AMPMI/WebSite.EndPoint/Views/Blog/BlogList.cshtml
  AMPMI/WebSite.EndPoint/Views/Blog/ShowBlog.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_Layout.cshtml
Labels: enhancement

#165 Debug save new user from admin panel
  AMPMI/WebSite.EndPoint/Areas/Admin/Controllers/UserController.cs
Labels: enhancement

#167 add favIcon , selected menus in admin and company layout , and check …
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Aboutus/ShowAboutUs.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/AdminPanel/ChangePassword.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/AdminPanel/Panel.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Banner/BannerList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Blog/BlogList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Blog/EditBlog.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/CategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Category/Edit.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Notification/ShowPage.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/NotConfirmedProductList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/SubCategory/EditSubCategory.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/SubCategory/SubCategoryList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/CompanyPictures.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/CompanyTeaser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/EditUser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/User/UserList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Models/Profile/PasswordEditVm.cs
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyPanel/Panel.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyPicture/Pictures.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/ChangePassword.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditCompanyProfile.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/CompanyProfile/EditTeaser.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Notification/NotifList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/EditProduct.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Product/ProductList.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_Layout.cshtml
  AMPMI/WebSite.EndPoint/wwwroot/images/cropped-fav-180x180.png
  AMPMI/WebSite.EndPoint/wwwroot/images/cropped-fav-192x192.png
  AMPMI/WebSite.EndPoint/wwwroot/images/cropped-fav-270x270.png
  AMPMI/WebSite.EndPoint/wwwroot/images/cropped-fav-32x32.png
Labels: enhancement

#172 Change style layout home
  AMPMI/WebSite.EndPoint/Areas/Admin/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Areas/Company/Views/Shared/_layout.cshtml
  AMPMI/WebSite.EndPoint/Views/AboutUs/Index.cshtml
  AMPMI/WebSite.EndPoint/Views/Blog/BlogList.cshtml
  AMPMI/WebSite.EndPoint/Views/Blog/ShowBlog.cshtml
  AMPMI/WebSite.EndPoint/Views/Company/CompanyDetail.cshtml
  AMPMI/WebSite.EndPoint/Views/Company/CompanyList.cshtml
  AMPMI/WebSite.EndPoint/Views/ContactUs/ContactUs.cshtml
  AMPMI/WebSite.EndPoint/Views/Home/Index.cshtml
  AMPMI/WebSite.EndPoint/Views/Shared/_Layout.cshtml
Labels: enhancement
